version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data # Монтируем папку для сохранения данных Redis
    #restart: always 
  server:
    build: 
      context: .
      dockerfile: Dockerfile.orchestor
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_network
    #restart: always
    volumes:
      - ./data:/app/data  # Монтируем папку для сохранения данных
    

  agent:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - redis
      - server
    networks:
      - my_network
    deploy:
      replicas: 2
    #restart: always
  

  

networks:
  my_network:
