version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/app/dataredis # Монтируем папку для сохранения данных Redis
    networks:
      - my_network
    #restart: always 

  server:
    build: 
      context: .
      dockerfile: Dockerfile.orchestor
    ports:
      - "8041:8041"
    depends_on:
      - redis
  
  
    networks:
      - my_network
    restart: always
    volumes:
      - ./data:/app/dataserver  # Монтируем папку для сохранения данных

  agent:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - redis
      - server
    networks:
      - my_network
    deploy:
      replicas: 1
    #restart: 

networks:
  my_network:
    driver: bridge
