FROM golang:latest

WORKDIR /app

# Копируем только go.mod и go.sum, чтобы воспользоваться кэшированием при сборке
COPY go.mod .
COPY go.sum .

# Устанавливаем зависимости
RUN go mod download

# Копируем остальные файлы проекта
COPY . .
RUN go get -u github.com/go-redis/redis
# Сборка приложения
RUN go build -o main .

# Эффективнее использовать CMD с аргументами, чем передавать go run
CMD ["./main"]

# Экспонируем порт, на котором работает приложение
EXPOSE 8041